baseURL = 'http://forest0923.github.io/memo/'
languageCode = 'en-us'
defaultContentLanguage = 'en'
title = 'Memo'
theme = 'hugo-book'

[params]
  BookTheme = 'dark'
  BookToC = true
  BookSearch = true

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1

[languages]
  [languages.en]
    languageName = 'English'
    contentDir = 'content'
    weight = 1
  [languages.jp]
    languageName = 'Japanese'
    contentDir = 'content.jp'
    weight = 2

[menu]
  [[menu.before]]
    name = "GitHub"
    url = "https://github.com/Forest0923"
    weight = 10

  [[menu.before]]
    name = "GitLab"
    url = "https://gitlab.com/forest0923"
    weight = 20
