baseURL = 'http://forest0923.github.io/memo/'
title = 'Memo'
description = 'Technical notes written by Forest0923'
theme = 'docsy'

defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true
enableMissingTranslationPlaceholders = true
enableRobotsTXT = true
enableGitInfo = true

#############
# Taxonomy
#############

[taxonomies]
tag = "tags"
category = "categories"

[params.taxonomy]
taxonomyCloudTitle  = ["Categories", "Tags Cloud"] 
taxonomyCloud       = ["categories", "tags"]
taxonomyPageHeader  = ["categories", "tags"]

############################################
# Configure how URLs look like per section.
############################################

[permalinks]
blog = "/:section/:year/:month/:day/:slug/"

###################################
# Image processing configuration.
###################################

[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

###########################
# Service configuration
###########################

[services]
[services.googleAnalytics]
# Comment out the next line to disable GA tracking. Also disables the feature described in [params.ui.feedback].
id = "UA-00000000-0"

###########################
# Language configuration
###########################

[languages]
[languages.ja]
contentDir = 'content/ja'
languageName ="Japanese"
[languages.en]
contentDir = 'content/en'
languageName ="English"

##########################
# Markdown parser
##########################
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    # https://xyproto.github.io/splash/docs/all.html
    style = "native"
    guessSyntax = false


#########################
# Other parameters
#########################

[params]
copyright = "Forest0923"

github_repo = "https://github.com/forest0923/memo"
# github_project_repo = "https://github.com/google/docsy"
github_branch= "master"

offlineSearch = true

# User interface configuration
[params.ui]
breadcrumb_disable = false
footer_about_disable = true
navbar_logo = true
navbar_translucent_over_cover_disable = false
sidebar_menu_compact = true
sidebar_menu_foldable = true
sidebar_search_disable = false

[params.ui.feedback]
enable = false

[params.ui.readingtime]
enable = false

[params.links]
[[params.links.developer]]
  name ="Twitter"
  url = "https://twitter.com/forest0923"
  icon = "fab fa-twitter"
  desc = "Follow us on Twitter to get the latest news!"
[[params.links.developer]]
  name = "GitHub"
  url = "https://github.com/forest0923"
  icon = "fab fa-github"
  desc = "Development takes place here!"
[[params.links.developer]]
  name = "GitLab"
  url = "https://gitlab.com/forest0923"
  icon = "fab fa-gitlab"
  desc = "Development takes place here!"

[params.katex]
enable = true

[params.mermaid]
enable = true
theme = 'dark'

####################################
# hugo module configuration
####################################

[module]
[module.hugoVersion]
extended = true
min = "0.73.0"
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    source = 'node_modules/bootstrap'
    target = 'assets/vendor/bootstrap'
  [[module.mounts]]
    source = 'node_modules/@fortawesome/fontawesome-free'
    target = 'assets/vendor/Font-Awesome'
  [[module.mounts]]
    source = "i18n"
    target = "i18n"
  [[module.mounts]]
    source = 'layouts'
    target = 'layouts'
  [[module.mounts]]
    source = 'static'
    target = 'static'