name: Deploy Github Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pages: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages
      - name: ls
        run: ls -al
      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v1.2.9
        with:
          # Name of the artifact to deploy
          artifact_name: github-pages
